### ISSUE TITLE
Problema al obtener mis 50$

### ISSUE THREAD

**Issue by SergioZaera** [gdsa-upc/gdsa-suport#97]
![image](https://user-images.githubusercontent.com/44504682/48767847-ecc05c80-ecb7-11e8-9ca0-9195ab7defc9.png)
![image](https://user-images.githubusercontent.com/44504682/48767912-15485680-ecb8-11e8-8381-cc265acdc50c.png)

Al acceder con mi dirección de correo personal, me deja acceder a los 50$ pero si cambio a la dirección de correo del grupo me aparece un mensaje diciendo: "El código de cupón que has introducido no es válido"

**Comment by lauramontolio** [comment]
A mi me pasa lo mismo que a Sergio, como podemos solucionarlo?

**Comment by noe** [comment]
¿Podéis probar con esto: https://stackoverflow.com/a/49587145/674487 ?

**Comment by xavigiro** [comment]
Ja he demanat cupons addicionals i me'ls ha donat. Demaneu-los a partir del missatge que us passo a continuació. Compto que només els demanaran la @lauramontolio i en @SergioZaera , que són els que s'han queixat. Si algú més en necessita, que respongui primer a aquest mateix tiquet i després que agafi el cupó.

----------------

Dear Students,


Here is the URL you will need to access in order to request a Google Cloud Platform coupon. You will be asked to provide your school email address and name. An email will be sent to you to confirm these details before a coupon is sent to you.

[Student Coupon Retrieval Link](https://google.force.com/GCPEDU?cid=9Ke1FH%2B1X5nRuorfmyGteC9h6thy11dvVRnRLwn%2FIB1UJ9CEgPMgLX7EPcmPmACi)

You will be asked for a name and email address, which needs to match the domain. A confirmation email will be sent to you with a coupon code.

You can request a coupon from the URL and redeem it until: 2/1/2019

Coupon valid through: 10/1/2019

You can only request ONE code per unique email address.

Please contact me if you have any questions or issues.



Thanks,

Dr. Xavier Giro-i-Nieto

**Comment by xavigiro** [comment]
Els tres cupons que quedaven els assigno a en Yu Bai, Manel Salvador i Pau Maza, per tal que puguin crear un nou equip 7.
